feat: configure sublime text
Signed-off-by: James Ramirez <james.ramirez@grendel-consulting.com>

diff --git a/.chezmoiscripts/run_once_after_install-nvm-node.sh.tmpl b/.chezmoiscripts/run_once_after_install-nvm-node.sh.tmpl
--- a/.chezmoiscripts/run_once_after_install-nvm-node.sh.tmpl
+++ b/.chezmoiscripts/run_once_after_install-nvm-node.sh.tmpl
@@ -2,6 +2,14 @@
 set -euo pipefail
 
 source "${NVM_DIR}/nvm.sh"
-nvm install 'lts/iron'
 
-echo "Defaulting to Node $(node -v)" # with the side-effect of ensuring nvm loads node once
+if command -v nvm >/dev/null 2>&1; then
+    nvm install 'lts/iron'
+
+    if command -v node >/dev/null 2>&1; then
+        echo "Defaulting to Node $(node -v)" # with the side-effect of ensuring nvm loads node once
+    fi
+else
+   echo "Error: NVM is not installed or not in PATH" >&2
+   exit 1
+fi
diff --git a/.chezmoiscripts/run_once_after_install-terraform.sh.tmpl b/.chezmoiscripts/run_once_after_install-terraform.sh.tmpl
--- a/.chezmoiscripts/run_once_after_install-terraform.sh.tmpl
+++ b/.chezmoiscripts/run_once_after_install-terraform.sh.tmpl
@@ -1,7 +1,13 @@
 #!/usr/bin/env zsh
 set -euo pipefail
 
-tfswitch --latest
+if command -v tfswitch >/dev/null 2>&1; then
+    tfswitch --latest
 
-echo "Defaulting to $(terraform -v)"
-
+    if command -v terraform >/dev/null 2>&1; then
+        echo "Defaulting to $(terraform -v)"
+    fi
+else
+    echo "Error: TfSwitch is not installed or not in PATH" >&2
+    exit 1
+fi
